version: "3"
services:
  postgres:
    image: library/postgres:11.7-alpine
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=postgres
      - DATABASE_HOST=postgres
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
#  migrate:
#    restart: on-failure
#    build: ./migrator
#    depends_on:
#      - postgres
#    links:
#      - postgres
#  nginx:
#    restart: always
#    build:
#      dockerfile: Dockerfile.dev
#      context: ./nginx
#    ports:
#      - "3050:80"
#  api:
#    restart: on-failure
#    depends_on:
#      - postgres
#    build:
#      dockerfile: Dockerfile
#      context: ./server
#    environment:
#      - BIND_ADDR=:5000
#      - LOG_LEVEL=debug
#      - DATABASE_URL=user=postgres password=docker host=postgres dbname=postgres port=5432 sslmode=disable
#      - TEST_DATABASE_URL=user=postgres password=docker host=postgres dbname=restapi_test port=5432 sslmode=disable
#  client:
#    build:
#      dockerfile: Dockerfile.dev
#      context: ./client
#    volumes:
#      - /app/node_modules
#      - ./client:/app
volumes:
  data:
#    external: true
